### ISSUE TITLE
Give players money for doing certain things

### ISSUE THREAD

**Issue by DevvyDont** [DevvyDont/Minestrike#3]
For now these can be based on or be relatively close to cs:go values until we can properly balance

- Winning/losing a round
- Getting a kill

to give a player money, you simply just need a reference to the player object, then you can do

```java
Minestrike plugin = Minestrike.getPlugin(Minestrike.class);
Player p;  // Some reference to player object
int moneyToGive;  // However much money you want to give
plugin.getGameManager().getPlayerManager().getCSPlayer(p).addMoney(moneyToGive);
```

**Comment by impuffs** [comment]
will different weapons provide different amounts of money as they do in CS, or will it be a flat rate like it is in Valorant? Also, is the money for winning or losing dynamic with the amount of wins and losses? If you survive as a terrorist without the bomb being defused should it still be 0?

possibly more inmportantly: is the money given at the end of the round for kills, as well as the round plays, or throughout the round as it is in CS?

**Comment by DevvyDont** [comment]
I'd personally say we should give support for allowing certain weapon kills to award certain amounts of money since it gives more power to server owners to customize the plugin to play like how they want it to play. Once implemented however, all weapons can give the same amount for now until some balance testing is done. For the second point, I personally don't think we need to make round bonus money be dynamic, as we don't want the economy to be too complex, but if we do decide to change it, it is a really easy tweak to make.

Just for the sake of being easier, I would award players money during the round, immediately after they get a kill. Round objects each have their own method with their own behavior for handling player kills, which means we don't even have to do any complicated math or data storage or anything when a round ends
