### ISSUE TITLE
Set default max hp for players from 20 -> 100

### ISSUE THREAD

**Issue by DevvyDont** [DevvyDont/Minestrike#6]
We will use a max hp of 100 for our game to streamline the hp that players have
When players log in, they simply just need to have their max hp set immediately

since setting player max HP scales the players hearts to always display 1 heart per 2HP, it is also probably a good idea to do this as well, so we don't have 5 rows of hearts on the screen
```java
Player p;
p.setHealthScaled(true);  // Makes sure the client is displaying the health scale just in case
p.setHealthScale​(20);  // Forces the client to display their health as if they had 20HP
```

**Comment by impuffs** [comment]
Max HP is set to 100 and is functional, however, the code to change the display to 10 hearts does not. Whenever joining the server, the health displays 10 'full' hearts, and 40 'empty' hearts, until damage is taken, or health is regenerated.

**Comment by DevvyDont** [comment]
Since you mentioned that taking damage or regenerating health fixes the health scale, maybe perhaps try setting the player's health to 100 *after* changing the health scale? That might force the health to update properly immediately
